PROXY="lmancuso@130.192.137.199"
CERT_PATH="/home/lore/Scaricati/mancuso_federated"

#ssh -i $CERT_PATH -J $PROXY lmancuso@coordinator "cd /mnt/dataset ; mv subset0 subset"

ssh -i $CERT_PATH -J $PROXY lmancuso@node01 "cd /mnt/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@node02 "cd /mnt/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@node03 "cd /mnt/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@node04 "cd /mnt/dataset ; rm -rfv ./*"

ssh -i $CERT_PATH -J $PROXY lmancuso@device1 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device2 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device3 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device4 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device5 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device6 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device7 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device8 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device9 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device10 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device11 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device12 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device13 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device14 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device15 "cd /home/lmancuso/dataset ; rm -rfv ./*"
ssh -i $CERT_PATH -J $PROXY lmancuso@device16 "cd /home/lmancuso/dataset ; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device17 "cd /home/lmancuso/dataset ; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device18 "cd /home/lmancuso/dataset ; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device19 "cd /home/lmancuso/dataset ; rm -rfv ./*"
#ssh -i $CERT_PATH -J $PROXY lmancuso@device20 "cd /home/lmancuso/dataset ; rm -rfv ./*"
