#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@coordinator:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/coordinator-progresses

#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device1:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device1-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device2:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device2-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device3:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device3-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device4:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device4-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device5:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device5-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device6:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device6-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device7:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device7-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device8:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device8-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device9:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device9-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device10:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device10-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device11:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device11-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device12:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device12-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device13:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device13-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device14:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device14-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device15:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device15-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device16:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device16-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device17:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device17-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device18:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device18-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device19:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device19-progresses
#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device20:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_Imagenet/device20-progresses


#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@gpu-worker:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/gpu_worker_ResNet50V2_512
