rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@coordinator:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/coordinator-progresses

rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device1:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device1-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device2:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device2-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device3:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device3-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device4:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device4-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device5:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device5-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device6:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device6-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device7:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device7-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device8:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device8-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device9:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device9-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device10:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device10-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device11:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device11-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device12:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device12-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device13:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device13-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device14:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device14-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device15:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device15-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device16:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device16-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device17:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device17-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device18:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device18-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device19:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device19-progresses
rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@device20:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/16_nodes_ResNet50V2_IMG/device20-progresses


#rsync -azv --append-verify --stats --human-readable --info=progress2 --exclude="res" -e 'ssh -i /home/lore/.ssh/mancuso_federated -J lmancuso@130.192.137.199' lmancuso@gpu-worker:/home/lmancuso/federated-learning/ /home/lore/Projects/Progresses/gpu_worker_ResNet50V2_512
